### ISSUE TITLE
Support ansible.builtin. prefixes for tasks

### ISSUE THREAD

**Issue by blekinge** [MSDehghan/AnsiblePlugin#10]
Hi

At the moment, when using Quick-javadoc (ctrl-Q) the plugin provides nice documentation for this task

```yaml
    - name: Check for single yarn_timeline_server
      fail: msg="Single host check failed."
      when: "groups['hostgroup_yarn_timeline_servers'] |length  != 1"
```

but reports "No documentation found" for

```
    - name: Check for single yarn_timeline_server
      ansible.builtin.fail: msg="Single host check failed."
      when: "groups['hostgroup_yarn_timeline_servers'] |length  != 1"
```
