### ISSUE TITLE
Syntax highlighting breaks after char |

### ISSUE THREAD

**Issue by pappou99** [MSDehghan/AnsiblePlugin#16]
a task written like follwing will cause to break the syntax highlighting after the "pipe" symbol right next to "shell: "

```
- name: Set vnc passwords tightvnc
  shell: |
    set -o pipefail
    echo {{ item.vnc_default_password }} | vncpasswd -f > /home/{{ item.username }}/.vnc/passwd
  args:
    chdir: "/home/{{ item.username }}/.vnc"
    creates: "/home/{{ item.username }}/.vnc/passwd"
    executable: /bin/bash
  with_items: "{{ vnc_users }}"
  when: vnc_server == "tightvnc"
```
![Bildschirmfoto von 2021-10-28 14-36-03](https://user-images.githubusercontent.com/28729133/139260698-ada51de5-52de-49b6-8b9c-d96e10b1a7b6.png)
